name: RUN V3a

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "5 5 * * *"
    - cron: "0 10 * * *"
    - cron: "8 18 * * *"

jobs:
  process:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      SRC_NAME: db-src
      OUT_NAME: db-out-da

    steps:
      - uses: actions/checkout@v4
      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          repository: haijiaolu/${{ env.SRC_NAME }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Checkout out repo
        uses: actions/checkout@v4
        with:
          repository: haijiaolu/${{ env.OUT_NAME }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.OUT_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Set up committer
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Run script A
        if: github.event.schedule == '5 5 * * *'
        run: |
          pushd ${{ env.SRC_NAME }} && 
          bash scripts2/run-daily-top.sh ${{ env.OUT_NAME }} &&
          popd

      - name: Run script B
        if: github.event.schedule == '0 10 * * *'
        run: |
          pushd ${{ env.SRC_NAME }} && 
          bash scripts2/run-daily-pages.sh ${{ env.OUT_NAME }} &&
          popd

      - name: Run script C
        if: github.event.schedule == '8 18 * * *'
        run: |
          pushd ${{ env.SRC_NAME }} && 
          bash scripts2/run-daily-hot.sh ${{ env.OUT_NAME }} &&
          popd

      - name: Commit and push
        run: bash push-repo.sh ${{ env.OUT_NAME }}
